const FORBIDDEN = 'FORBIDDEN';
const BAD_REQUEST = 'BAD_REQUEST';
const INVALID_TOKEN = 'INVALID_TOKEN';
const RESOURCE_NOT_FOUND = 'NOT_FOUND';
const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

export {
	BAD_REQUEST,
	FORBIDDEN,
	INTERNAL_SERVER_ERROR,
	INVALID_TOKEN,
	RESOURCE_NOT_FOUND,
};
